---
name: "INFRA DESTROY (prod)"
on:
  workflow_dispatch:
    inputs:
      instance_type:
        type: choice
        description: "instance type"
        options:
          - t2.micro
          - t2.small
        default: "t2.micro"

      instance_ami:
        type: string
        description: "instance ami"
        required: true
        default: "ami-0ee4f2271a4df2d7d"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.PROD_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.PROD_SECRET_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.PROD_REGION}}

    steps:
      - name: "Checkout From Repository"
        uses: actions/checkout@v3
      - name: "Terraform Installation"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2
      - name: Terraform init
        run: |
          terraform init \
              -backend-config="bucket=${{ secrets. PROD_S3_BUCKET }}" \
              -backend-config="key=terraform.tfstate" \
              -backend-config="region=${{ secrets.PROD_REGION }}" \
              -backend-config="access_key=${{ secrets.PROD_ACCESS_KEY }}" \
              -backend-config="secret_key=${{ secrets.PROD_SECRET_KEY }}" \

        working-directory: ./terraform/
      - name: "Terraform destroy"
        run: |
          terraform destroy \
            -var "instance_type=${{github.event.inputs.instance_type}}" \
            -var "instance_ami=${{github.event.inputs.instance_ami}}" \
             -auto-approve
        working-directory: ./terraform/
